language: cpp
dist: trusty
cache: ccache

os:
  - linux
  
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
    packages:
    - qt510base
    - qt510charts-no-lgpl
    - qt510multimedia
    - dh-make

branches:
  only:
    - 'master'

before_script:
      export DISPLAY=:99.0
      && sh -e /etc/init.d/xvfb start;

script:
  - source /opt/qt510/bin/qt510-env.sh;
  - qmake ./WPanda.pro -r
  - make -j2
  - ./test/WPanda-test;
