version: '3.8'

services:
  wiredpanda:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - /dev/fuse
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=offscreen
    ports:
      - "8080:8080"  # Adjust as necessary for your app
    stdin_open: true
    tty: true
